// Migration 009 — FIBO LOAN entity expansion.
//
// Imports curated owl:Class nodes from the FIBO LOAN module
// (https://github.com/edmcouncil/fibo, MIT licensed) as :Entity nodes.
// Filtered to mortgage- / loan- / lending-relevant classes via a keyword
// match on rdfs:label + skos:definition.
//
// FIBO classes are formal ontology concepts; their `description` here is
// the verbatim skos:definition. The FIBO IRI is preserved in the
// `fibo_iri` property so future migrations can resolve back to the source.
//
// Idempotent (MERGE on Entity name).

MERGE (e:Entity {name: 'AllBorrowersMonthlyIncome'}) ON CREATE SET e.description = 'total monthly qualifying income for all borrowers on the loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/AllBorrowersMonthlyIncome', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/AllBorrowersMonthlyIncome');
MERGE (e:Entity {name: 'AmortizationType'}) ON CREATE SET e.description = 'classifier of amortization algorithms', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/AmortizationType', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/AmortizationType');
MERGE (e:Entity {name: 'AutoLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/AutoLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/AutoLoanPurpose');
MERGE (e:Entity {name: 'AutomatedUnderwritingSystem'}) ON CREATE SET e.description = 'software system that collects the information necessary to approve a loan application and supports a mortgage lender\'s analysis of a new loan application', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/AutomatedUnderwritingSystem', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/AutomatedUnderwritingSystem');
MERGE (e:Entity {name: 'BorrowerAssessment'}) ON CREATE SET e.description = 'assessment report detailing information about the borrower and their credit history that may be relevant to the loan application', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerAssessment', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerAssessment');
MERGE (e:Entity {name: 'BorrowerDataProtectionRequirement'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/BorrowerDataProtectionRequirement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/BorrowerDataProtectionRequirement');
MERGE (e:Entity {name: 'BorrowerDisclosureRequirement'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/BorrowerDisclosureRequirement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/BorrowerDisclosureRequirement');
MERGE (e:Entity {name: 'BorrowerMonthlyIncome'}) ON CREATE SET e.description = 'total monthly qualifying income of a potential borrower', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerMonthlyIncome', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerMonthlyIncome');
MERGE (e:Entity {name: 'BorrowerRight'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/BorrowerRight', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/BorrowerRight');
MERGE (e:Entity {name: 'BridgingLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/BridgingLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/BridgingLoanPurpose');
MERGE (e:Entity {name: 'CardProduct'}) ON CREATE SET e.description = 'financial product involving the issuance of credit, debit, or other payment cards', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CardProduct', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CardProduct');
MERGE (e:Entity {name: 'CashOutStatus'}) ON CREATE SET e.description = 'classifier indicating the extent to which funds are released to the borrower on a new loan origination that refinances an existing loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/CashOutStatus', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/CashOutStatus');
MERGE (e:Entity {name: 'ChargeCategory'}) ON CREATE SET e.description = 'Examples include closing costs, interest, taxes, and other service-related fees.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/ChargeCategory', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/ChargeCategory');
MERGE (e:Entity {name: 'ClosedEndCredit'}) ON CREATE SET e.description = 'credit agreement in which the loan principal cannot be increased after funds are dispersed in full when the loan closes', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/ClosedEndCredit', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/ClosedEndCredit');
MERGE (e:Entity {name: 'ClosedEndMortgageLoan'}) ON CREATE SET e.description = 'loan secured by real estate with no ability for the borrower to receive additional funds under the loan at a later date', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/ClosedEndMortgageLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/ClosedEndMortgageLoan');
MERGE (e:Entity {name: 'ClosedEndReverseMortgage'}) ON CREATE SET e.description = 'reverse mortgage that provides a lump sum payment to the borrower at closing, with no ability for the borrower to receive additional funds under the mortgage at a later date', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/ClosedEndReverseMortgage', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/ClosedEndReverseMortgage');
MERGE (e:Entity {name: 'CoMaker'}) ON CREATE SET e.description = 'party that signs a borrower\'s promissory note, providing additional security and potentially improving the quality of the debt', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/Comaker', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/Comaker');
MERGE (e:Entity {name: 'CollateralizedLoan'}) ON CREATE SET e.description = 'secured loan that is secured with cash or other acceptable collateral (real property, securities or other assets) provided by the borrower as specified in the collateral agreement', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/CollateralizedLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/CollateralizedLoan');
MERGE (e:Entity {name: 'CombinedLoanToValueRatio'}) ON CREATE SET e.description = 'ratio of the total amount of debt that is secured by the asset(s) and the appraised value of the asset(s) securing the financing', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/CombinedLoanToValueRatio', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/CombinedLoanToValueRatio');
MERGE (e:Entity {name: 'CommercialCreditCardAgreement'}) ON CREATE SET e.description = 'credit card agreement for a card issued to, or in conjunction with, a formal organization, such as a small business, middle market business, local, state, or national government, or large corporation', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CommercialCreditCardAgreement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CommercialCreditCardAgreement');
MERGE (e:Entity {name: 'CommercialLoan'}) ON CREATE SET e.description = 'loan extended to a corporation, commercial enterprise, joint venture, or other organization as opposed to a consumer', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CommercialLoans/CommercialLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CommercialLoans/CommercialLoan');
MERGE (e:Entity {name: 'ConstructionLoan'}) ON CREATE SET e.description = 'loan covering construction and development costs, secured by a mortgage on the property financed', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/ConstructionLoans/ConstructionLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/ConstructionLoans/ConstructionLoan');
MERGE (e:Entity {name: 'ConstructionLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/ConstructionLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/ConstructionLoanPurpose');
MERGE (e:Entity {name: 'ConsumerCreditCardAgreement'}) ON CREATE SET e.description = 'credit card agreement for a card issued for household, family, or other personal expenditures that is accessed by a borrower\'s use of a credit card', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/ConsumerCreditCardAgreement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/ConsumerCreditCardAgreement');
MERGE (e:Entity {name: 'ConsumerCreditEqualTreatmentRequirement'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditEqualTreatmentRequirement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditEqualTreatmentRequirement');
MERGE (e:Entity {name: 'ConsumerCreditProtectionLaw'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditProtectionLaw', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditProtectionLaw');
MERGE (e:Entity {name: 'ConsumerCreditReferenceAgency'}) ON CREATE SET e.description = 'Applicable regulations: vary by jurisdiciton. for example, only being allowed ot divulge actual judgements against a party, but not things that are not substantiated by judgements. For example, slow payments which are not covered by some judgement against the party. There will be different regulatory requirments about: 1. What the CR Agency can hold 2. Who they can divulge it to 3. What information they must provide the borrower at his/her request Some of the third thing there is covered in the EU the Data Protection Directive and local acts that implement this.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditReferenceAgency', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditReferenceAgency');
MERGE (e:Entity {name: 'ConsumerCreditRequirement'}) ON CREATE SET e.description = 'Requirement set out on the lender about how they must treat the appliction to a loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditRequirement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/ConsumerCreditRequirement');
MERGE (e:Entity {name: 'ConsumerLoan'}) ON CREATE SET e.description = 'loan to one or more individuals for household, family, or other personal expenditures, excluding mortgages and student loans', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/ConsumerLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/ConsumerLoan');
MERGE (e:Entity {name: 'CreditCard'}) ON CREATE SET e.description = 'card issued by a financial service provider that enables the cardholder to borrow funds', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCard', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCard');
MERGE (e:Entity {name: 'CreditCardAccount'}) ON CREATE SET e.description = 'card account whose terms and conditions are defined in a credit card agreement that is represented by a credit card', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardAccount', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardAccount');
MERGE (e:Entity {name: 'CreditCardAgreement'}) ON CREATE SET e.description = 'account-specific credit facility that specifies the terms and conditions under which the credit card is offered to the cardholder by the issuer', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardAgreement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardAgreement');
MERGE (e:Entity {name: 'CreditCardNetwork'}) ON CREATE SET e.description = 'classifier for the network that authorizes, processes, and sets the terms of credit card transactions, as well as transfers payments between shoppers, merchants, and their banks', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardNetwork', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardNetwork');
MERGE (e:Entity {name: 'CreditCardProduct'}) ON CREATE SET e.description = 'card product allowing the holder to purchase goods or services on credit', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardProduct', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/CreditCardProduct');
MERGE (e:Entity {name: 'CreditCardReceivablePurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/CreditCardReceivablePurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/CreditCardReceivablePurpose');
MERGE (e:Entity {name: 'CreditReferenceAgencyRequirements'}) ON CREATE SET e.description = 'REquirements other than data protection, governing what a credit reference agency can or cannot do.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/CreditReferenceAgencyRequirements', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/CreditReferenceAgencyRequirements');
MERGE (e:Entity {name: 'CreditRiskAssessment'}) ON CREATE SET e.description = 'risk assessment that focuses on determining the likelihood of a potential borrower repaying a loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/CreditRiskAssessment', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/CreditRiskAssessment');
MERGE (e:Entity {name: 'DataProtectionRequirement'}) ON CREATE SET e.description = 'Requirements defining how data about individuals is held. Example is the EU DA directive and laws, which make the data the property of the individual that data is about. Covers - what information i sheld - who information can be divulged to. - the individual\'s rights in respect of that information Privacy regulations cover most of this. EU defines "Personal Data" and "Sensitive Personal Data". For credit reference agencies the latter would be covered. More detail about whether they can divulge facts which are not subject to formal judgements etc.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/DataProtectionRequirement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/DataProtectionRequirement');
MERGE (e:Entity {name: 'DebitCard'}) ON CREATE SET e.description = 'payment card issued by a financial service provider that enables the cardholder to access funds in a demand deposit account', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/DebitCard', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/DebitCard');
MERGE (e:Entity {name: 'DisclosureRequirement'}) ON CREATE SET e.description = 'Requirement for disclosure to borrowers or potential borrowers. There are two kinds of disclosure requirement: 1. Disclosure about the information held on the borrower 2. Disclsure about the product.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/DisclosureRequirement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/DisclosureRequirement');
MERGE (e:Entity {name: 'EnvironmentalProgram'}) ON CREATE SET e.description = 'broad scale initiative, activity, or investment aimed at improving environmental sustainability, reducing ecological harm, or addressing environmental challenges', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/EnvironmentalProgram', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/EnvironmentalProgram');
MERGE (e:Entity {name: 'EnvironmentalProject'}) ON CREATE SET e.description = 'specific initiative, activity, or investment aimed at improving environmental sustainability, reducing ecological harm, or addressing environmental challenges', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/EnvironmentalProject', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/EnvironmentalProject');
MERGE (e:Entity {name: 'GoodFaithEstimate'}) ON CREATE SET e.description = 'GFE - representation by the lender on the costs and implications of settlement (early termination) of the loan.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/GoodFaithEstimate', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/GoodFaithEstimate');
MERGE (e:Entity {name: 'GovernmentSponsoredLoan'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/GovernmentSponsoredLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/GovernmentSponsoredLoan');
MERGE (e:Entity {name: 'GreenLoan'}) ON CREATE SET e.description = 'credit agreement and/or contingent facility (such as a bonding line, guarantee line or letter of credit) made available exclusively to finance, re-finance or guarantee, in whole or in part, new and/or existing eligible green projects that are aligned to the four core components of the Green Loan Principles (GLP)', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/GreenLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/GreenLoan');
MERGE (e:Entity {name: 'GreenProjectUseOfProceedsProvision'}) ON CREATE SET e.description = 'use of proceeds provision specifying that funds obtained through financing, such as through a credit agreement, offering, warrant, or other instrument are intended to be used for Green Projects (including other related and supporting expenditures, including research and development)', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/GreenProjectUseOfProceedsProvision', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/GreenProjectUseOfProceedsProvision');
MERGE (e:Entity {name: 'GuaranteedLoan'}) ON CREATE SET e.description = 'loan that is secured with respect to repayment of principal and interest by guaranty', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/GuaranteedLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/GuaranteedLoan');
MERGE (e:Entity {name: 'HMDACoveredLoanContract'}) ON CREATE SET e.description = 'a closed-end mortgage loan or open-end line of credit that is not an excluded transaction for HMDA reporting under US section 1003.3(c) of the Revised Home Mortgage Disclosure Act of 2015', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-CoveredLoanContract', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-CoveredLoanContract');
MERGE (e:Entity {name: 'HMDADisposition'}) ON CREATE SET e.description = 'a type of action taken regarding an application for a HMDA covered loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-Disposition', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-Disposition');
MERGE (e:Entity {name: 'HMDAPreApprovalRequest'}) ON CREATE SET e.description = 'a request for pre-approval of a home purchase loan up to a certain amount, and subject to certain non-credit related conditions', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-PreApprovalRequest', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-PreApprovalRequest');
MERGE (e:Entity {name: 'HMDAReport'}) ON CREATE SET e.description = 'a report prepared to satisfy HMDA regulatory reporting requirements as described US section 1003.3(c) of the Revised Home Mortgage Disclosure Act of 2015', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-Report', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HMDA-Report');
MERGE (e:Entity {name: 'HomeEquityLineOfCredit'}) ON CREATE SET e.description = 'line of credit granted to a homeowner secured by the equity value in a borrower\'s home or other property', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/HomeEquityLineOfCredit', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/HomeEquityLineOfCredit');
MERGE (e:Entity {name: 'HomeEquityLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/HomeEquityLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/HomeEquityLoanPurpose');
MERGE (e:Entity {name: 'HowSubmitted'}) ON CREATE SET e.description = 'category indicating whether the applicant or borrower submitted the application for the covered loan directly to the reporting financial institution', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HowSubmitted', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/HowSubmitted');
MERGE (e:Entity {name: 'IncomeVerificationReport'}) ON CREATE SET e.description = 'report providing the methodology and supporting documentation used to verify the borrower\'s income', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/IncomeVerificationReport', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/IncomeVerificationReport');
MERGE (e:Entity {name: 'IndividualPersonCreditRating'}) ON CREATE SET e.description = 'credit rating that provides an opinion of the creditworthiness of a person', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/IndividualPersonCreditRating', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/IndividualPersonCreditRating');
MERGE (e:Entity {name: 'IssuingFinancialInstitution'}) ON CREATE SET e.description = 'issuer and financial services provider that issues payment cards or performs, facilitates, or supports issuing services including but not limited to issuing banks and issuing processors', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/IssuingFinancialInstitution', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/IssuingFinancialInstitution');
MERGE (e:Entity {name: 'LenderLienPosition'}) ON CREATE SET e.description = 'classifier indicating whether the lender has the primary lien position with respect to an asset used as collateral for the loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LenderLienPosition', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LenderLienPosition');
MERGE (e:Entity {name: 'LenderRight'}) ON CREATE SET e.description = 'Rights on the lender to protect them against loss. furthe rNtoes: Logically, considering the two parties, they both have protecxtion mechanisms. so while the lender has protecxtion mechanisms through mortgage insurance, and the consumer has protextion mechanisms such as good faith estimates. also the agencies (see Consumer Protection Agency), an instance of which is the CFPB in the US (just set up). Lender rights are: - expressed in the Contract Consumer protection develops becaues the contract is written by the potential Lender. So the rights are introcued to rectify the imbalance between the two parties. Same goes for insurance. consumer protection laws (governe dby the relevant consumer protection agency. So the lender protexts itself as it writes th contract AND does the things it needs to do to protext itself, but on the approval process, and with later instruments such as insurance. Interestingly., it is the Borrower who pays for this by paying for credit reports etc. So the borrower protects itself by other mechanisms. Caveat emptor - displaced by regulation (the buyer is protected by regulation). Uberimae Fidae - in the utmost good faith. Mortgage Insurance is an additional means of mitigating the risk, that the lended may have., so if the information assessed is not accurate, or if the borrower\'s situation changes for the worse. then the risk rating may go down. So the Mortgage Insurance is a further strategy which mitigates any shortfall in the Lender Righrs that you may have - ie someone guarantees. In the US you can also avoid that by having paid a deposit. PIMI: Principal, Interst and Morgage Insurance. So the Borrower pays towards the MI, esxcept if they have paid a given amount as deposit. there are 2 types of MI: 1. protects the lender in the event of borrower degault 2. Insurance for "Incapacity to pay the mortage" (these can be bought off the shelf - can combine health, unemployment etc.). - this is the Borrower mitigating their own risk. Prevents foreclosure. Similar to general sickness etc. Where the lender charges for MI, the cost is passed onto the Borrower. e.g. if there is a % valuation (e.g. 70% in Aus, 80% in US for example) then no insurance is required.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/LenderRight', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/LenderRight');
MERGE (e:Entity {name: 'LineItem'}) ON CREATE SET e.description = 'description of a product or service including its unit cost, number of units and total cost', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LineItem', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LineItem');
MERGE (e:Entity {name: 'Loan'}) ON CREATE SET e.description = 'debt instrument whereby one party extends money or credit to another party (or parties) with the understanding that the borrowed money will be repaid according to the terms of the contract', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/Loan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/Loan');
MERGE (e:Entity {name: 'LoanApplication'}) ON CREATE SET e.description = 'request by a potential borrower to a potential lender to borrow money containing information used to decide whether to grant the loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplication', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplication');
MERGE (e:Entity {name: 'LoanApplicationAtAgreementStage'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationAtAgreementStage', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationAtAgreementStage');
MERGE (e:Entity {name: 'LoanApplicationAtDisbursementStage'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationAtDisbursementStage', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationAtDisbursementStage');
MERGE (e:Entity {name: 'LoanApplicationPhase'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationPhase', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationPhase');
MERGE (e:Entity {name: 'LoanApplicationStatus'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationStatus', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanApplicationStatus');
MERGE (e:Entity {name: 'LoanAtApplicationStage'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanAtApplicationStage', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/LoanAtApplicationStage');
MERGE (e:Entity {name: 'LoanDefaultProceeding'}) ON CREATE SET e.description = '[no definition] Further Review This is typically part of mortgagte servicing. THere would typically be a whole department dealing with this. Dealing with default, helping borrowers make payment Collections Default admin Foreclosure Reselling All dealt with by several sub departments. This requires subject matter experts in this area. 1. scoping Identify default as a possible state. This hands off to other business processes. Once you get into the default scenario we are talking about a proces that is going to fall into place over a period of time. The bank works out what to do with the default scenario, e.g. whether it restructures, forecloses, seeks restitution from the security (collateral). It does nto help us to understand the structure of the loan, rather tha consequences of the loan. If we were to further explore the default detail we would bring in other SMEs. And we would have to model a process flow. 1.1 impact on the pool of an MBS Loan Default Proceeding (special ase of legal thing) is an aspect of Default Management / Administratoin. there is also the State of the Loan. Sale / something / fulfilment / fiunduing / approved = servicing mode. Something happens (non payment) =&gt, Default Grace Period followed by negotiation. Some threshold whereby after a given amount of delinquency it needs to go into some other process moving towards foreclosure. Do State Diagram. Stages of loan.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/LoanDefaultProceeding', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/LoanDefaultProceeding');
MERGE (e:Entity {name: 'LoanMarketCategory'}) ON CREATE SET e.description = 'category indicating the market domain in which the loan product is offered', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanMarketCategory', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanMarketCategory');
MERGE (e:Entity {name: 'LoanOffering'}) ON CREATE SET e.description = 'offering related to a loan product that may be a tailored to particular circumstances, aimed at a group of borrowers or individual borrower', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanProductOffering', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanProductOffering');
MERGE (e:Entity {name: 'LoanPaidInFull'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/LoanPaidInFull', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/LoanPaidInFull');
MERGE (e:Entity {name: 'LoanPaymentSchedule'}) ON CREATE SET e.description = 'regular or explicit (ad hoc) payment schedule associated with a given loan-specific account', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LoanPaymentSchedule', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LoanPaymentSchedule');
MERGE (e:Entity {name: 'LoanPhase'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/LoanPhase', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/LoanPhase');
MERGE (e:Entity {name: 'LoanProduct'}) ON CREATE SET e.description = 'financial product that is realized as a loan that a party may acquire from a lending institution with specific characteristics and terms', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanProduct', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanProduct');
MERGE (e:Entity {name: 'LoanProductDisclosureRight'}) ON CREATE SET e.description = 'Right to fair representation of the facts about Loan products before entrering into agreements for same.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanProductDisclosureRight', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanProductDisclosureRight');
MERGE (e:Entity {name: 'LoanProductRepresentations'}) ON CREATE SET e.description = 'Representations about the loan product and the appropriateness of this for the borrower.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/LoanProductRepresentations', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/LoanProductRepresentations');
MERGE (e:Entity {name: 'LoanPurpose'}) ON CREATE SET e.description = 'A selection of different types of loan purpose, being the purpose for which and manner in which loan (credit) draw-down amounts are to be used. This shows the purpose for which credit is to be used, and implies certain kinds of fact that relate to that specific type of loan e.g. mortgages. These are also identified as tranche types in tranches of a credit facility.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/LoanPurpose');
MERGE (e:Entity {name: 'LoanRegulatoryRequirement'}) ON CREATE SET e.description = 'A regulatory requirement defined in regulations by a comsumer credit act or other legislation.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/LoanRegulatoryRequirement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/LoanRegulatoryRequirement');
MERGE (e:Entity {name: 'LoanSecuredByRealEstate'}) ON CREATE SET e.description = 'loan that, at origination, is secured wholly or substantially by a lien or liens on real property for which the lien or liens are central to the extension of the credit - that is, the borrower would not have been extended credit in the same amount or on terms as favorable without the lien or liens on real property', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/LoanSecuredByRealEstate', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/LoanSecuredByRealEstate');
MERGE (e:Entity {name: 'LoanSpecificCustomerAccount'}) ON CREATE SET e.description = 'account held by the borrower associated with a specific loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LoanSpecificCustomerAccount', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LoanSpecificCustomerAccount');
MERGE (e:Entity {name: 'LoanToValueRatio'}) ON CREATE SET e.description = 'ratio, expressed as a percentage, between the principal amount of the loan and the appraised value of the asset securing the financing', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LoanToValueRatio', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/LoanToValueRatio');
MERGE (e:Entity {name: 'ManufacturedHomeLegalClassification'}) ON CREATE SET e.description = 'category indicating whether the covered loan is secured by a manufactured home only or with land as well', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/ManufacturedHomeLegalClassification', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/ManufacturedHomeLegalClassification');
MERGE (e:Entity {name: 'MarineFinance'}) ON CREATE SET e.description = 'A loan for the purchase of a boat or other vessel.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/MarineFinance/MarineFinancing', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/MarineFinance/MarineFinancing');
MERGE (e:Entity {name: 'Mortgage'}) ON CREATE SET e.description = 'grant of financial interest in real property to a party that is not an owner of that real property and is recorded by a registration authority', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/Mortgage', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/Mortgage');
MERGE (e:Entity {name: 'MortgageIndemnityGuarantee'}) ON CREATE SET e.description = 'insurance-backed guarantee that protects lenders if the mortgage repayments cease for some reason, perhaps due to death or a homeowner being made redundant at work', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageIndemnityGuarantee', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageIndemnityGuarantee');
MERGE (e:Entity {name: 'MortgageIndemnityGuarantor'}) ON CREATE SET e.description = 'guarantor and insurer that provides mortgage insurance in the form of a mortgage indemnity guarantee (MIG)', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageIndemnityGuarantor', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageIndemnityGuarantor');
MERGE (e:Entity {name: 'MortgageIndemnityInsurancePolicy'}) ON CREATE SET e.description = 'insurance policy providing the mortgage indemnity guarantee', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageIndemnityInsurancePolicy', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageIndemnityInsurancePolicy');
MERGE (e:Entity {name: 'MortgageLoanPurpose'}) ON CREATE SET e.description = 'the purpose for which mortgage loan proceeds will be used, such as real property purchase, dwelling construction, or loan refinancing', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/MortgageLoanPurpose');
MERGE (e:Entity {name: 'MortgageProduct'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/MortgageProduct', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/MortgageProduct');
MERGE (e:Entity {name: 'MotorVehicleLoan'}) ON CREATE SET e.description = 'collateralized, simple-interest loan that is repaid in monthly installments over a period of typically three to five years, for the purpose of purchasing a vehicle', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/MotorVehicleLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/MotorVehicleLoan');
MERGE (e:Entity {name: 'MotorhomeLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/MotorhomeLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/MotorhomeLoanPurpose');
MERGE (e:Entity {name: 'NationwideMortgageLicensingSystemAndRegistryIdentifier'}) ON CREATE SET e.description = 'the number permanently assigned by the Nationwide Mortgage Licensing System and Registry (NMLS) for each company, branch, and individual that maintains a single account on NMLS.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/NMLSR-ID', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/NMLSR-ID');
MERGE (e:Entity {name: 'OpenEndCredit'}) ON CREATE SET e.description = 'credit agreement that may be extended up to an agreed credit limit and paid down at any time within the period of the line, if any, and on which interest is charged only on the outstanding balance', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/OpenEndCredit', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/OpenEndCredit');
MERGE (e:Entity {name: 'OpenEndMortgageLoan'}) ON CREATE SET e.description = 'loan secured by real estate with a provision that the outstanding loan amount may be increased upon mutual agreement of the lender and the borrower', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/OpenEndMortgageLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/OpenEndMortgageLoan');
MERGE (e:Entity {name: 'OpenEndReverseMortgage'}) ON CREATE SET e.description = 'reverse mortgage structured like a home equity line of credit in that it provides the borrower with additional funds after closing (either as fixed monthly payments, under a line of credit, or both)', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/OpenEndReverseMortgage', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/OpenEndReverseMortgage');
MERGE (e:Entity {name: 'OrdinaryLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/OrdinaryLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/OrdinaryLoanPurpose');
MERGE (e:Entity {name: 'OwnershipInterest'}) ON CREATE SET e.description = 'classifier indicating the nature of the applicant\'s or borrower\'s ownership or leasehold interest in an asset used as collateral for the loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/OwnershipInterest', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/OwnershipInterest');
MERGE (e:Entity {name: 'PaymentCard'}) ON CREATE SET e.description = 'legal document issued by a financial services provider that enables the cardholder to access the funds in the customer\'s designated bank accounts, or through a credit account and make payments by electronic funds transfer and access automated teller machines (ATMs)', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/PaymentCard', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/PaymentCard');
MERGE (e:Entity {name: 'PaymentCardAgreement'}) ON CREATE SET e.description = 'account-specific credit agreement that specifies the terms and conditions under which the payment card is offered to the cardholder by the issuer', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/PaymentCardAgreement', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/CardAccounts/PaymentCardAgreement');
MERGE (e:Entity {name: 'PaymentHistory'}) ON CREATE SET e.description = 'record of actual payments of principal, interest, and other related amounts made by a borrower to a lender or servicer in order to fulfill their re-payment obligation', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/PaymentHistory', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/PaymentHistory');
MERGE (e:Entity {name: 'PreApprovalContract'}) ON CREATE SET e.description = 'written commitment to lend when specified conditions are met, such as finding suitable property, and unchanged creditworthiness', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PreApprovalContract', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PreApprovalContract');
MERGE (e:Entity {name: 'PreApprovalRequest'}) ON CREATE SET e.description = 'request from a potential borrower that a lender commit to pre-approving the borrower for a loan of up to a specified amount of money', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PreApprovalRequest', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PreApprovalRequest');
MERGE (e:Entity {name: 'PrePaymentTerms'}) ON CREATE SET e.description = 'principal repayment terms related to payment of the loan prior to maturity', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/PrepaymentTerms', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/PrepaymentTerms');
MERGE (e:Entity {name: 'Prepayment'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/Prepayment', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanEvents/Prepayment');
MERGE (e:Entity {name: 'PrivateStudentLoan'}) ON CREATE SET e.description = 'student loan that is not considered a government-backed / regulated loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/StudentLoans/PrivateStudentLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/StudentLoans/PrivateStudentLoan');
MERGE (e:Entity {name: 'PropertyUsage'}) ON CREATE SET e.description = 'a category indicating the manner in which the borrower intends to utilize the property', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/PropertyUsage', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/MortgageOrigination/PropertyUsage');
MERGE (e:Entity {name: 'PublicRecordCategory'}) ON CREATE SET e.description = 'classifier of public records relevant to a loan application, e.g. tax lien, wage garnishment, foreclosure', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PublicRecordCategory', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/PublicRecordCategory');
MERGE (e:Entity {name: 'RegB'}) ON CREATE SET e.description = 'US regulation concerning "Equal credit opportunity act" Electronic delivery of disclosures', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/RegB', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/RegB');
MERGE (e:Entity {name: 'RegZ'}) ON CREATE SET e.description = 'US Fed regulation "Truth in Lending Act" uniform standards for electronic delivery of disclosures', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/RegZ', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/RegZ');
MERGE (e:Entity {name: 'RegulatedStudentLoan'}) ON CREATE SET e.description = 'student loan (1) whose lender is a government agency or instrumentality, and/or (2) that is treated uniquely due to tax regulations', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/StudentLoans/RegulatedStudentLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/StudentLoans/RegulatedStudentLoan');
MERGE (e:Entity {name: 'ResidentialHouseboatLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/ResidentialHouseboatLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/ResidentialHouseboatLoanPurpose');
MERGE (e:Entity {name: 'ReverseMortgageLoan'}) ON CREATE SET e.description = 'loan secured by real estate that pays money to the borrower against a set principal limit based on the value of existing equity in the underlying collateral', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/ReverseMortgageLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/Mortgages/ReverseMortgageLoan');
MERGE (e:Entity {name: 'RightOfCreditRecordCorrection'}) ON CREATE SET e.description = 'The right to have a credit record corrected.', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/RightOfCreditRecordCorrection', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoansRegulatory/RightOfCreditRecordCorrection');
MERGE (e:Entity {name: 'SecuredConsumerLoan'}) ON CREATE SET e.description = 'loan to one or more individuals for household, family, or other personal expenditures in which the borrower pledges some asset via a security agreement as collateral for the loan, or that is secured via third-party guarantee', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/SecuredConsumerLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/SecuredConsumerLoan');
MERGE (e:Entity {name: 'SecuredLoan'}) ON CREATE SET e.description = 'loan in which the borrower pledges some asset via a security agreement as collateral for the loan, or that is secured via third-party guarantee', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/SecuredLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/SecuredLoan');
MERGE (e:Entity {name: 'Servicer'}) ON CREATE SET e.description = 'party that collects principal and interest payments on behalf of the lender', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/Servicer', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/Servicer');
MERGE (e:Entity {name: 'StudentLoan'}) ON CREATE SET e.description = 'loan provided for the purposes of education, allowing students and parents/guardians to borrow money for college', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/StudentLoans/StudentLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/StudentLoans/StudentLoan');
MERGE (e:Entity {name: 'StudentLoanPurpose'}) ON CREATE SET e.description = '', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/StudentLoanPurpose', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/LoanProducts/StudentLoanPurpose');
MERGE (e:Entity {name: 'SustainabilityLinkedLoan'}) ON CREATE SET e.description = 'credit agreement and/or contingent facility (such as a bonding line, guarantee line or letter of credit) for which the economic characteristics can vary depending on whether the borrower achieves ambitious, material and quantifiable predetermined sustainability performance objectives aligned with Sustainability-Linked Loan Principles (SSLP)', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/SustainabilityLinkedLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/SustainabilityLinkedLoan');
MERGE (e:Entity {name: 'SustainabilityPerformanceTarget'}) ON CREATE SET e.description = 'collection of quantitative target values used to calibrate the level of achievement a borrower makes with respect to a key performance indicator, by date, including, but not limited to, the methodology used to calculate its value at any point over the lifetime of a loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/SustainabilityPerformanceTarget', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/SustainabilityPerformanceTarget');
MERGE (e:Entity {name: 'SustainabilityStructuringAgent'}) ON CREATE SET e.description = 'financial institution appointed to help design, implement, and monitor the sustainability aspects of a syndicated green loan', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/SustainabilityStructuringAgent', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/SustainabilityStructuringAgent');
MERGE (e:Entity {name: 'TotalDebtExpenseRatio'}) ON CREATE SET e.description = 'ratio of all monthly debt payments of all borrowers, including proposed expenses, with respect to the income of the borrowers as relied upon to make a credit decision', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/TotalDebtExpenseRatio', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/TotalDebtExpenseRatio');
MERGE (e:Entity {name: 'TotalOutstandingPrincipal'}) ON CREATE SET e.description = 'the principal balance of all loans secured by the property', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/TotalOutstandingPrincipal', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/TotalOutstandingPrincipal');
MERGE (e:Entity {name: 'TransitionLoan'}) ON CREATE SET e.description = 'credit agreement and/or contingent facility (such as a bonding line, guarantee line or letter of credit) designed to help a business or organization shift from carbon-intensive or environmentally harmful practices to more sustainable and environmentally friendly operations', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/TransitionLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/TransitionLoan');
MERGE (e:Entity {name: 'TransitionUseOfProceedsProvision'}) ON CREATE SET e.description = 'use of proceeds provision specifying that funds obtained through financing, such as through a credit agreement, offering, warrant, or other instrument are intended to be used to fund specific projects, investments, or operational changes that support a company\'s transition toward sustainability', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/TransitionUseOfProceedsProvision', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/GreenLoans/TransitionUseOfProceedsProvision');
MERGE (e:Entity {name: 'UnderwritingAutomation'}) ON CREATE SET e.description = 'classifier indicating whether a loan was underwritten manually or using an automated underwriting system', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/UnderwritingAutomation', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/UnderwritingAutomation');
MERGE (e:Entity {name: 'UnderwritingDecision'}) ON CREATE SET e.description = 'classifier providing a loan approval recommendation determined either manually or by an automated underwriting system', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/UnderwritingDecision', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/UnderwritingDecision');
MERGE (e:Entity {name: 'UniversalLoanIdentifier'}) ON CREATE SET e.description = 'unique identifier given to unequivocally identify a specific loan secured by real estate', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/UniversalLoanIdentifier', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages/UniversalLoanIdentifier');
MERGE (e:Entity {name: 'UnsecuredConsumerLoan'}) ON CREATE SET e.description = 'loan to one or more individuals for household, family, or other personal expenditures granted based on the strength of the borrower\'s credit history or reputation in the community', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/UnsecuredConsumerLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansSpecific/ConsumerLoans/UnsecuredConsumerLoan');
MERGE (e:Entity {name: 'UnsecuredLoan'}) ON CREATE SET e.description = 'loan granted based on the strength of the borrower\'s credit history or reputation in the community', e.fibo_iri = 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/UnsecuredLoan', e.source = 'FIBO LOAN' ON MATCH SET e.fibo_iri = coalesce(e.fibo_iri, 'https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/Loans/UnsecuredLoan');

MERGE (m:SchemaMigration {migration_id: '009_fibo_loan_entities'}) ON CREATE SET m.applied_at = datetime(), m.description = 'FIBO LOAN entity import — 130 mortgage/loan-relevant classes from edmcouncil/fibo (MIT)';
